W6D5/auth_app/config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  get "users/create"
  get "users/new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :session
end

W6D5/auth_app/app/models/session.rb
class Session < ApplicationRecord
end

W6D5/auth_app/app/models/user.rb
class User < ApplicationRecord
  attr_reader :password
  validates :username, presence: true
  validates :password_digest, presence: { message: "Password cant be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true
  after_initialize :ensure_session_token
  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if !user
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password).to_s
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

W6D5/auth_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def login!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logged_in?
    !!current_user
  end

  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_current_user!
    redirect_to new_session_url if !current_user
  end
end

W6D5/auth_app/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

W6D5/auth_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user
      login!(user)
      redirect_to user_url(user)
    else
      render json: "Credentials were wrong"
    end
    
  end

  def new
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W6D5/auth_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]
  before_action :set_user, only: :create

  def create
    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      render json: errors.full_messages
    end
  end

  def new
    @user = User.new
  end

  private

  def set_user
    @user = User.find_by(user_params)
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W6D5/auth_app/app/helpers/session_helper.rb
module SessionHelper
end

W6D5/auth_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if !current_user.nil? %>
      <ul>
        <li>logged in as: <%= current_user.username %> </li>
        <li>
          <form action="<%= session_url%>" method="POST">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" value="log out">
          </form>
        </li>
      </ul>
    <% end %>
    <%= yield %>
  </body>
</html>

W6D5/auth_app/app/views/users/_form.html.erb
<% action=(user.persisted? user_url(user) : users_url) %>
<% method=(user.persisted? 'PATCH' : 'POST') %>
<% message=(user.persisted? 'UPDATEUSER' : 'CREATE USER')%>
<form action="<% action %>">
  <input name='_method' type="hidden" value='<%=method%>'>
  <input name="authenticity_token" type="hidden"  value= "<%= form_authenticity_token %>">
  <label for="user_username">Username</label>
  <input id="user_username" name="user[username]" type="text">
  <br>
  <label for="user_password">Password</label>
  <input type="password" id="user_password" name="user[password]">
  <br>
  <input type="submit" value="<%=message%>">
</form>

W6D5/auth_app/app/views/users/create.html.erb
<h1>Create User</h1>
<%= render 'form', user: @user %>

W6D5/auth_app/app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

W6D5/auth_app/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p>Hello dear user</p>